### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by kenijo** [nmaxcom/brackets-autosaver#1]
Hi,

This extension is very welcomed. I love it.
I have a suggestion though. Coming from Notepad++, it has the auto save feature but it saves the files as temporary files in a Notepad++ folder .
This has three benefits:
- The original file is only modified when you actually explicitly save the document. If you are working on the document and want to open it again to see the original content, you can do so.
- If you are working on the same file with someone else, people are not constantly overwriting each others.
- If you create a temporary new document, you don't have to worry about saving it.
- In case of crash on new documents, they are not lost.

If you think this is valuable, would you consider adding this feature?
Thanks

**Comment by nmaxcom** [comment]
Hi @kenijo,

Thanks for your comments and suggestion. I thought about it a bit when I wrote it. As of now, the extension works in a "safe way" by using Bracket's own saving method.

The point of this extension was to provide an automated trigger for file processors/watchers like gulp, grunt etc. AFAIK the Jetbrains products' native autosave works the same way without the potential problems you mention.

If I save the changes as another file, the person would have to keep always that in mind plus the cluttering of the file tree.

I'm not sure I understand how people would overwrite each other, using what other than a version system?

In the temporary document part, you would have similar issues with either method.

I also don't see why new documents would get lost on a crash.

**Comment by kenijo** [comment]
Hi, Thanks for your answer.
I understand where you come from and the way you design the extension.

To avoid cluttering of the file tree I had in mind saving the temp file in a dedicated temp folder hidden from the user.
Regarding users overwriting each others, that would only happen on a shared file. I know it is not the way to handle a file but unfortunately it can happen. Although this use case just come to mind, I don't think I encountered it since using proper versioning systems.

**Comment by nmaxcom** [comment]
It's definitely something to keep in mind. Let's see how it rolls as it is and how more people respond to it.

Thanks.
