### ISSUE TITLE
Paste and undo/redo are not autosaved

### ISSUE THREAD

**Issue by xednijmeijer** [nmaxcom/brackets-autosaver#5]
If one makes a change in a document, and undoes it later, the change resulting from that will not get saved. Only if one were to maually save or type a space or something, the document is saved. As I use live preview all the time and undo changes a lot, it can be confusing as of why the change doesn't appear on the preview.

Also, when pasting a snippet of code in the editor, that is not autosaved as well. Finally, batch replacing of code doesn't autosave.

Brackets version: sprint 9 build 1.9.0-17312 (release 189f6d39a)
Extention version: 1.1.5

**Comment by nmaxcom** [comment]
Thanks for letting me know, I'll look into it.

**Comment by nmaxcom** [comment]
Sorry for the late reply. I seldom use Brackets and I've been up to my ears with work!

I have redone the method by which the extension detect changes and it detects the changes with cut and paste. Should work without a problem, just updated it :)

Let me know if you need anything else.

**Comment by xednijmeijer** [comment]
It works wonderfully now, thanks a lot!
