### ISSUE TITLE
It doesn't work at all for me

### ISSUE THREAD

**Issue by RinkuTalks** [nmaxcom/brackets-autosaver#7]
I'm new to brackets but auto saving seems like a must have.  I got many other extensions to work but this one doesn't.  All I need to do is enable autsave in settings right?  its set to default 400ms but nothing happens when I edit a  basic file.

**Comment by mittalyashu** [comment]
Facing the same issue. To make this package work, sometimes I need to re-start the brackets.

**Comment by nmaxcom** [comment]
Hi,

I coded this extension precisely for the lack of an obvious autosave feature myself. There are several issues claiming the same problem, so it's safe to assume that the new Brackets made some breaking API  changes.

Let me look into it

**Comment by nmaxcom** [comment]
It works perfectly in my end. I have uninstalled it and installed it clean in the usual manner and it works.

Please open the debugging console:

1. Click the menu Debug in Bracket's main view
1. Choose the first option "Show developer tools"
1. In the new window, make sure you are looking at the "Console" tab
1. You should see something like this:

![image](https://user-images.githubusercontent.com/8936090/28346955-85cb1cb8-6c34-11e7-8895-746516f18bf5.png)

If something is not working right, it should appear there and would give me lots of help to solve your particular case. It may be interfering with other extensions you have installed or something else.

Give it a screenshot and post it here (you can just paste it here and github will automatically upload it)

**Comment by nmaxcom** [comment]
I just updated the extension with a new method to detect changes, it may solve this weird bug.

Let me know how it goes please.

**Comment by drozumek** [comment]
I have the issue during installation.
Brackets 1.10, There is a message: Instalation failed, problem during launching extension.
