### ISSUE TITLE
Works unreliably

### ISSUE THREAD

**Issue by quantbo** [nmaxcom/brackets-autosaver#8]
Sometimes it works, and sometimes it doesn't. Whether a file is auto-saved seems to be random.

My platform: Windows 10
Brackets version:
Release 1.9 build 1.9.0-17312 (release 189f6d39a) 
build timestamp: Tue Mar 21 2017 10:29:45 GMT+0000

**Comment by nmaxcom** [comment]
Thanks for informing. I'm merging with duplicate #7
