### ISSUE TITLE
"CTRL + E" for change color

### ISSUE THREAD

**Issue by presentMaklay** [nmaxcom/brackets-autosaver#9]
Hi, I really liked the "brackets-autosaver".
I found a defect, I hope you correct it.
If you nag "CTRL + E" and select a color for CSS, auto-saving does not work.

**Comment by nmaxcom** [comment]
It works fine for me:

![bracketsctrle](https://user-images.githubusercontent.com/8936090/39699101-fe241fbc-51f7-11e8-81c7-161848f1893c.gif)

Let me see what the console shows you when you try and use autosave; we'll troubleshoot from there :)

**Comment by nmaxcom** [comment]
I updated the gif because it went down. Please let me know if you still have that issue and what your console (Debug menu -> Show developer tools) says about it
